language: android
android:
  components:
  - tools
  - build-tools-26.0.1
  - platform-tools
  - tools
  - android-26
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
install:
  - sdkmanager --list || true
script:
  - travis_wait gradle build connectedCheck
deploy:
  provider: releases
  api_key:
    secure: SIS4vlZudKtpCqA2vsW133YNd43K4Xez/vSJ8oF/HPYZpJIGjx3cVkpcSI6GANKscZRBGPf6T0R64IxRyWliClatK2HCoZKGRWkpStMpdrHEjlLXs7Odx+EZvarSfF1Ol8dM45ocpcIFGqM8zb9x9+OIip/NGnUoFrW41nFMRs0R+zPJMHwomvOhWiLU4ShPHRHkvcbLzk4EJd7bPPuZeZA0PaMooND6Nfw46DxYpyal1hvr21vDQ6UrG63cAFhO2TDMb9kE2OxTGX2L5IATCfcsiTnuBUdYvu8gcDJbYZFH8rQNkRhl5LeWhF1KcNkNQgCP4Zv8FhJ8mKsu/fA9aSHQZiawWtLqtpMaGbBMaW1xFL/r+xN5hPB6Ye4lLO+sphl98Bs29My2L0Sd6VBmGVv/qvWXrvrgFGv6Yh+x01ZyFrNHWjySBx4PpTQAzSPS8693A4qYLpqAjw+mcBs1Uef7xX1DecGVeD08q6jJa6RaNfabnHQCo1Teb1ResxePQmGLResp82PfWIbLc/iiqmncl7PNBVl3dQRxCFsVDnBXUpCmOVR/Ll2beIW5pO9BCLUYeKpgDy/8vvL/XtKsFEeWNb2WUqmFtvn5MZRWRfKErw17wWFBd5VjEdgIQePWRnL5KvTJRUlHzSDmDNJF34+LaIO/wSq80FXbqiDOUZ0=
  file: $HOME/app/build/outputs/apk/app-release-unsigned.apk
  skip_cleanup: true
  on:
    tags: true
    repo: Project-ARTist/CodeLib
